# Site settings
title:          Sung Jun
description:    "Sung Jun Develop Blog"
baseurl:        ""
url:            "https://ykwimk.github.io"

# Author
author:
  name:         Sung Jun, Lee
  url:          https://ykwimk.github.io
  email:        ykwimk@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
